name: "coverage"
on:
  pull_request_target:
    branches:
      - develop
      - main
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          test-script: npm test
          message: ${{ steps.coverage.outputs.report }}
